//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FlexberryGisTestStand
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Comment.
    /// </summary>
    // *** Start programmer edit section *** (Comment CustomAttributes)

    // *** End programmer edit section *** (Comment CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CommentE", new string[] {
            "Text as \'Text\'",
            "Type as \'Type\'"})]
    public class Comment : ICSSoft.STORMNET.DataObject
    {
        
        private string fText;
        
        private IIS.FlexberryGisTestStand.tStatus fType;
        
        private IIS.FlexberryGisTestStand.Request fRequest;
        
        // *** Start programmer edit section *** (Comment CustomMembers)

        // *** End programmer edit section *** (Comment CustomMembers)

        
        /// <summary>
        /// Text.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Text CustomAttributes)

        // *** End programmer edit section *** (Comment.Text CustomAttributes)
        [StrLen(255)]
        public virtual string Text
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Text Get start)

                // *** End programmer edit section *** (Comment.Text Get start)
                string result = this.fText;
                // *** Start programmer edit section *** (Comment.Text Get end)

                // *** End programmer edit section *** (Comment.Text Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Text Set start)

                // *** End programmer edit section *** (Comment.Text Set start)
                this.fText = value;
                // *** Start programmer edit section *** (Comment.Text Set end)

                // *** End programmer edit section *** (Comment.Text Set end)
            }
        }
        
        /// <summary>
        /// Type.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Type CustomAttributes)

        // *** End programmer edit section *** (Comment.Type CustomAttributes)
        public virtual IIS.FlexberryGisTestStand.tStatus Type
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Type Get start)

                // *** End programmer edit section *** (Comment.Type Get start)
                IIS.FlexberryGisTestStand.tStatus result = this.fType;
                // *** Start programmer edit section *** (Comment.Type Get end)

                // *** End programmer edit section *** (Comment.Type Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Type Set start)

                // *** End programmer edit section *** (Comment.Type Set start)
                this.fType = value;
                // *** Start programmer edit section *** (Comment.Type Set end)

                // *** End programmer edit section *** (Comment.Type Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.FlexberryGisTestStand.Request.
        /// </summary>
        // *** Start programmer edit section *** (Comment.Request CustomAttributes)

        // *** End programmer edit section *** (Comment.Request CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Request"})]
        public virtual IIS.FlexberryGisTestStand.Request Request
        {
            get
            {
                // *** Start programmer edit section *** (Comment.Request Get start)

                // *** End programmer edit section *** (Comment.Request Get start)
                IIS.FlexberryGisTestStand.Request result = this.fRequest;
                // *** Start programmer edit section *** (Comment.Request Get end)

                // *** End programmer edit section *** (Comment.Request Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Comment.Request Set start)

                // *** End programmer edit section *** (Comment.Request Set start)
                this.fRequest = value;
                // *** Start programmer edit section *** (Comment.Request Set end)

                // *** End programmer edit section *** (Comment.Request Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CommentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CommentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CommentE", typeof(IIS.FlexberryGisTestStand.Comment));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Comment.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfComment CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfComment CustomAttributes)
    public class DetailArrayOfComment : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.FlexberryGisTestStand.DetailArrayOfComment members)

        // *** End programmer edit section *** (IIS.FlexberryGisTestStand.DetailArrayOfComment members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Comment by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Comment.
        /// </summary>
        public DetailArrayOfComment(IIS.FlexberryGisTestStand.Request fRequest) : 
                base(typeof(Comment), ((ICSSoft.STORMNET.DataObject)(fRequest)))
        {
        }
        
        public IIS.FlexberryGisTestStand.Comment this[int index]
        {
            get
            {
                return ((IIS.FlexberryGisTestStand.Comment)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.FlexberryGisTestStand.Comment dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
