//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FlexberryGisTestStand
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T gender.
    /// </summary>
    // *** Start programmer edit section *** (tGender CustomAttributes)

    // *** End programmer edit section *** (tGender CustomAttributes)
    public enum tGender
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tGender.Male CustomAttributes)

        // *** End programmer edit section *** (tGender.Male CustomAttributes)
        Male,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tGender.Female CustomAttributes)

        // *** End programmer edit section *** (tGender.Female CustomAttributes)
        Female,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tGender.Unknown CustomAttributes)

        // *** End programmer edit section *** (tGender.Unknown CustomAttributes)
        Unknown,
    }
}
