version: '3'
services:
  GisTestStandPostgres:
    image: "flexberry/gis-test-stand-postgres-db:latest"
    volumes:
      - GisTestStandDB:/var/lib/pgsql/data/
    ports:
     - "5432:5432"
  GisTestStand:
    image: "flexberry/gis-test-stand:latest"
    command: /bin/sleep 11d
    ports:
     - "1818:80"

volumes:
  GisTestStandDB: 
