version: "3.2"
services:
  GisTestStandPostgres:
    image: "flexberry/gis-test-stand-postgres-db:latest"
  GisTestStand:
    image: "flexberry/gis-test-stand:latest"
    ports:
     - 1818:80
  GisTestStandGeoserver:
    image: "flexberry/gis-test-stand-geoserver:latest"
    ports:
      - 1819:8080
    environment:
      GEOSERVER_LOG_LOCATION: /dev/null
    depends_on:
      - GisTestStandPostgres
