version: '3'
services:
  GisTestStandPostgres:
    image: "flexberry/gis-test-stand-postgres-db:latest"
    volumes:
      - GisTestStandDB:/var/lib/pgsql/data/
  GisTestStand:
    image: "flexberry/gis-test-stand:latest"
    ports:
     - "1818:80"

volumes:
  GisTestStandDB: 
