version: '3'
services:
  GisTestStandPostgres:
    image: "flexberry/gis-test-stand-postgres-db:1.1"
    volumes:
      - GisTestStandDB:/var/lib/pgsql/data/
    ports:
     - "5432:5432"
  GisTestStand:
    image: "flexberry/gis-test-stand-odata:1.1"
    command: /bin/sleep 11d
    ports:
     - "1818:80"
  GisTestStandGeoserver:
    image: "flexberry/gis-test-stand-geoserver:1.1"
    port:
     - "1819:8080"


volumes:
  GisTestStandDB: 
