//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FlexberryGisTestStand
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Request.
    /// </summary>
    // *** Start programmer edit section *** (Request CustomAttributes)

    // *** End programmer edit section *** (Request CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RequestE", new string[] {
            "Date as \'Date\'",
            "Urgently as \'Urgently\'",
            "Task as \'Task\'",
            "Author as \'Author\'",
            "Author.Name as \'Name\'",
            "Address as \'Address\'",
            "Address.Place as \'Place\'"})]
    [AssociatedDetailViewAttribute("RequestE", "Comment", "CommentE", true, "", "Comment", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("RequestE", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("RequestE", "Address", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Place")]
    [View("RequestL", new string[] {
            "Date as \'Date\'",
            "Urgently as \'Urgently\'",
            "Task as \'Task\'",
            "Author.Name as \'Name\'",
            "Address.Place as \'Place\'"})]
    public class Request : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fDate = System.DateTime.Now;
        
        private bool fUrgently;
        
        private string fTask;
        
        private IIS.FlexberryGisTestStand.Author fAuthor;
        
        private IIS.FlexberryGisTestStand.Address fAddress;
        
        private IIS.FlexberryGisTestStand.DetailArrayOfComment fComment;
        
        // *** Start programmer edit section *** (Request CustomMembers)

        // *** End programmer edit section *** (Request CustomMembers)

        
        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (Request.Date CustomAttributes)

        // *** End programmer edit section *** (Request.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (Request.Date Get start)

                // *** End programmer edit section *** (Request.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (Request.Date Get end)

                // *** End programmer edit section *** (Request.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Date Set start)

                // *** End programmer edit section *** (Request.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (Request.Date Set end)

                // *** End programmer edit section *** (Request.Date Set end)
            }
        }
        
        /// <summary>
        /// Urgently.
        /// </summary>
        // *** Start programmer edit section *** (Request.Urgently CustomAttributes)

        // *** End programmer edit section *** (Request.Urgently CustomAttributes)
        public virtual bool Urgently
        {
            get
            {
                // *** Start programmer edit section *** (Request.Urgently Get start)

                // *** End programmer edit section *** (Request.Urgently Get start)
                bool result = this.fUrgently;
                // *** Start programmer edit section *** (Request.Urgently Get end)

                // *** End programmer edit section *** (Request.Urgently Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Urgently Set start)

                // *** End programmer edit section *** (Request.Urgently Set start)
                this.fUrgently = value;
                // *** Start programmer edit section *** (Request.Urgently Set end)

                // *** End programmer edit section *** (Request.Urgently Set end)
            }
        }
        
        /// <summary>
        /// Task.
        /// </summary>
        // *** Start programmer edit section *** (Request.Task CustomAttributes)

        // *** End programmer edit section *** (Request.Task CustomAttributes)
        [StrLen(255)]
        public virtual string Task
        {
            get
            {
                // *** Start programmer edit section *** (Request.Task Get start)

                // *** End programmer edit section *** (Request.Task Get start)
                string result = this.fTask;
                // *** Start programmer edit section *** (Request.Task Get end)

                // *** End programmer edit section *** (Request.Task Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Task Set start)

                // *** End programmer edit section *** (Request.Task Set start)
                this.fTask = value;
                // *** Start programmer edit section *** (Request.Task Set end)

                // *** End programmer edit section *** (Request.Task Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Author CustomAttributes)

        // *** End programmer edit section *** (Request.Author CustomAttributes)
        [PropertyStorage(new string[] {
                "Author"})]
        [NotNull()]
        public virtual IIS.FlexberryGisTestStand.Author Author
        {
            get
            {
                // *** Start programmer edit section *** (Request.Author Get start)

                // *** End programmer edit section *** (Request.Author Get start)
                IIS.FlexberryGisTestStand.Author result = this.fAuthor;
                // *** Start programmer edit section *** (Request.Author Get end)

                // *** End programmer edit section *** (Request.Author Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Author Set start)

                // *** End programmer edit section *** (Request.Author Set start)
                this.fAuthor = value;
                // *** Start programmer edit section *** (Request.Author Set end)

                // *** End programmer edit section *** (Request.Author Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Address CustomAttributes)

        // *** End programmer edit section *** (Request.Address CustomAttributes)
        [PropertyStorage(new string[] {
                "Address"})]
        [NotNull()]
        public virtual IIS.FlexberryGisTestStand.Address Address
        {
            get
            {
                // *** Start programmer edit section *** (Request.Address Get start)

                // *** End programmer edit section *** (Request.Address Get start)
                IIS.FlexberryGisTestStand.Address result = this.fAddress;
                // *** Start programmer edit section *** (Request.Address Get end)

                // *** End programmer edit section *** (Request.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Address Set start)

                // *** End programmer edit section *** (Request.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Request.Address Set end)

                // *** End programmer edit section *** (Request.Address Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Comment CustomAttributes)

        // *** End programmer edit section *** (Request.Comment CustomAttributes)
        public virtual IIS.FlexberryGisTestStand.DetailArrayOfComment Comment
        {
            get
            {
                // *** Start programmer edit section *** (Request.Comment Get start)

                // *** End programmer edit section *** (Request.Comment Get start)
                if ((this.fComment == null))
                {
                    this.fComment = new IIS.FlexberryGisTestStand.DetailArrayOfComment(this);
                }
                IIS.FlexberryGisTestStand.DetailArrayOfComment result = this.fComment;
                // *** Start programmer edit section *** (Request.Comment Get end)

                // *** End programmer edit section *** (Request.Comment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Comment Set start)

                // *** End programmer edit section *** (Request.Comment Set start)
                this.fComment = value;
                // *** Start programmer edit section *** (Request.Comment Set end)

                // *** End programmer edit section *** (Request.Comment Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RequestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestE", typeof(IIS.FlexberryGisTestStand.Request));
                }
            }
            
            /// <summary>
            /// "RequestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestL", typeof(IIS.FlexberryGisTestStand.Request));
                }
            }
        }
    }
}
