//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FlexberryGisTestStand
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T status.
    /// </summary>
    // *** Start programmer edit section *** (tStatus CustomAttributes)

    // *** End programmer edit section *** (tStatus CustomAttributes)
    public enum tStatus
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tStatus.Important CustomAttributes)

        // *** End programmer edit section *** (tStatus.Important CustomAttributes)
        Important,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tStatus.NotImportant CustomAttributes)

        // *** End programmer edit section *** (tStatus.NotImportant CustomAttributes)
        NotImportant,
    }
}
